PropertyManager/Models/Analyst.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace PropertyManager.Models
{
    public class Analyst
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        [Display (Name = "Phone Number")]
        public string PhoneNumber { get; set; }
        [ForeignKey("IdentityUser")]
        public string IdentityUserId { get; set; }
        public IdentityUser IdentityUser { get; set; }
    }
}

PropertyManager/Controllers/AnalystsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PropertyManager.Data;
using PropertyManager.Models;

namespace PropertyManager.Controllers
{
    public class AnalystsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AnalystsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Analysts
        public IActionResult Index()
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var analyst = _context.Analysts.Where(a => a.IdentityUserId == userId);
            if(analyst == null)
            {
                return View("Create");
            }
            else
            {
                var properties = _context.Properties.Where(p => p.WorkOrderCount >= 1).ToList();
                return View(properties);
            }
           
        }

        // GET: Analysts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var property = await _context.Properties.Where(p => p.Id == id).FirstOrDefaultAsync();
            if (property == null)
            {
                return NotFound();
            }

            return View();
        }

        // GET: Analysts/Create
        public IActionResult Create()
        {
            Analyst analyst = new Analyst();
            ViewData["IdentityUserId"] = new SelectList(_context.Set<IdentityUser>(), "Id", "Id");
            return View(analyst);
        }

        // POST: Analysts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,IdentityUserId")] Analyst analyst)
        {
            if (ModelState.IsValid)
            {
                var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
                analyst.IdentityUserId = userId;
                _context.Add(analyst);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdentityUserId"] = new SelectList(_context.Set<IdentityUser>(), "Id", "Id", analyst.IdentityUserId);
            return View(analyst);
        }

        // GET: Analysts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var analyst = await _context.Analysts.FindAsync(id);
            if (analyst == null)
            {
                return NotFound();
            }
            ViewData["IdentityUserId"] = new SelectList(_context.Set<IdentityUser>(), "Id", "Id", analyst.IdentityUserId);
            return View(analyst);
        }

        // POST: Analysts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,IdentityUserId")] Analyst analyst)
        {
            if (id != analyst.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(analyst);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AnalystExists(analyst.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdentityUserId"] = new SelectList(_context.Set<IdentityUser>(), "Id", "Id", analyst.IdentityUserId);
            return View(analyst);
        }

        // GET: Analysts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var analyst = await _context.Analysts
                .Include(a => a.IdentityUser)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (analyst == null)
            {
                return NotFound();
            }

            return View(analyst);
        }

        // POST: Analysts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var analyst = await _context.Analysts.FindAsync(id);
            _context.Analysts.Remove(analyst);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AnalystExists(int id)
        {
            return _context.Analysts.Any(e => e.Id == id);
        }

        public IActionResult Graph()
        {
            var workOrders = _context.Properties.Where(w => w.WorkOrderCount >= 1).ToList();

            return View(workOrders);
        }

        public IActionResult CreateRec()
        {
            Reccomendation reccomend = new Reccomendation();
            List<Property> properties = _context.Properties.Where(p => p.WorkOrderCount > 0).ToList();
            ViewData["Property"] = new SelectList(properties, "Id", "Address");
            return View(reccomend);
        }

        [HttpPost]
        public IActionResult CreateRec(Reccomendation reccomend)
        {
            _context.Reccomendations.Add(reccomend);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
       
        public IActionResult ViewWorkOrders(int id)
        {
            var allWO = _context.WorkOrders.Select(a => a).Include(a => a.Tenant).ThenInclude(a => a.Property).ToList();
            var workOrders = allWO.Where(w => w.Tenant.PropertyId == id).ToList();
            return View(workOrders);
        }
    }
}

PropertyManager/Views/Analysts/Create.cshtml
@model PropertyManager.Models.Analyst

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Analyst</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdentityUserId" class="control-label"></label>
                <select asp-for="IdentityUserId" class ="form-control" asp-items="ViewBag.IdentityUserId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PropertyManager/Views/Analysts/CreateRec.cshtml
@model PropertyManager.Models.Reccomendation

@{
    ViewData["Title"] = "CreateRec";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create Rec</h1>

<h4>Reccomendation</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateRec">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Rec" class="control-label"></label>
                <textarea asp-for="Rec" class="form-control" rows="5" placeholder="Type Here"></textarea>
                <span asp-validation-for="Rec" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PropertyId" class="control-label"></label>
                <select asp-for="PropertyId" class="form-control" asp-items="ViewBag.Property "></select>
                <span asp-validation-for="PropertyId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

PropertyManager/Views/Analysts/Delete.cshtml
@model PropertyManager.Models.Analyst

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Analyst</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdentityUser)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdentityUser.Id)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PropertyManager/Views/Analysts/Details.cshtml
@model PropertyManager.Models.Analyst

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Analyst</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdentityUser)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdentityUser.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

PropertyManager/Views/Analysts/Edit.cshtml
@model PropertyManager.Models.Analyst

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Analyst</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="IdentityUserId" class="control-label"></label>
                <select asp-for="IdentityUserId" class="form-control" asp-items="ViewBag.IdentityUserId"></select>
                <span asp-validation-for="IdentityUserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PropertyManager/Views/Analysts/Graph.cshtml
@model IEnumerable<PropertyManager.Models.Property>


@{
    ViewData["Title"] = "Graph";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
<h1>Graph</h1>
<div class="row">
    <canvas id="myChart"></canvas>
</div>

<div class="row">
    <div>
        <a asp-action="Index">Back to List</a>
    </div>
</div>
<script>
    var labels = [];
    var data = [];
    @foreach(var item in Model)
    {
        <text>
    labels.push('@item.Name');
    data.push('@item.WorkOrderCount');
    </text>
    }
    var ctx = document.getElementById('myChart').getContext('2d');
    var chart = new Chart(ctx, {
        // The type of chart we want to create
        type: 'radar',

        // The data for our dataset
        data: {
            labels: labels,
            datasets: [{
                label: data,
                backgroundColor: 'rgb(255, 99, 132)',
                borderColor: 'rgb(255, 99, 132)',
                data: [0, 10, 5, 2, 20, 30, 45]
            }]
        },

        // Configuration options go here
        options: {}
    });
</script>

PropertyManager/Views/Analysts/Index.cshtml
@model IEnumerable<PropertyManager.Models.Property>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Home</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.State)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ZipCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.WorkOrderCount)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.State)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ZipCode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WorkOrderCount)
            </td>
            <td>
                <a asp-action="ViewWorkOrders" asp-route-id="@item.Id">View Work Orders</a>
            </td>
        </tr>
}
    </tbody>
</table>
<div class="row">
    <div class="col">
        <input type="button" value="Work Order Matrix" class="btn btn-secondary" onclick="location.href='@Url.Action("Graph", "Analysts")'" />
    </div>
</div>

PropertyManager/Views/Analysts/ViewWorkOrders.cshtml
@model IEnumerable<PropertyManager.Models.WorkOrder>

@{
    ViewData["Title"] = "ViewWorkOrders";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Work Orders</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Issue)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsComplete)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TenantId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ContractorId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Issue)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsComplete)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TenantId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ContractorId)
            </td>
        </tr>
}
    </tbody>
</table>

<div class="col">
    <input type="button" value="Create Reccomendation" class="btn btn-secondary" onclick="location.href='@Url.Action("CreateRec", "Analysts")'" />
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>