PropertyManager/Controllers/AdminsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json.Linq;
using PropertyManager.Data;
using PropertyManager.Models;

namespace PropertyManager.Controllers
{
    public class AdminsController : Controller
    {
        private readonly ApplicationDbContext _context;
        public static readonly HttpClient httpClient = new HttpClient();

        public AdminsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Admins
        public async Task<IActionResult> Index()
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var admin = _context.Admins.Where(a => a.IdentityUserId == userId).FirstOrDefault();
            if(admin == null)
            {
                return View("Create");
            }
            else
            {
             var jobs = _context.WorkOrders.Select(j => j).Include(j => j.Tenant).ThenInclude(j => j.Property).ToListAsync();
             return View(await jobs);
            }
        }

        // GET: Admins/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var job = _context.WorkOrders.Where(j => j.Id == id).Include(j => j.Tenant).Include(j => j.Tenant.Property).FirstOrDefault();
            
            if (job == null)
            {
                return NotFound();
            }

            return View(job);
        }

        // GET: Admins/Create
        public IActionResult Create()
        {
            ViewData["IdentityUserId"] = new SelectList(_context.Set<IdentityUser>(), "Id", "Id");
            return View();
        }

        // POST: Admins/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,IdentityUserId")] Admin admin)
        {
            if (ModelState.IsValid)
            {
                var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
                var identityUser = _context.Users.Where(i => i.Id == userId).FirstOrDefault();
                admin.IdentityUserId = userId;
                admin.IdentityUser = identityUser;
                _context.Add(admin);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdentityUserId"] = new SelectList(_context.Set<IdentityUser>(), "Id", "Id", admin.IdentityUserId);
            return View(admin);
        }

        // GET: Admins/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var admin = await _context.Admins.FindAsync(id);
            if (admin == null)
            {
                return NotFound();
            }
            ViewData["IdentityUserId"] = new SelectList(_context.Set<IdentityUser>(), "Id", "Id", admin.IdentityUserId);
            return View(admin);
        }

        // POST: Admins/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,IdentityUserId")] Admin admin)
        {
            if (id != admin.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(admin);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AdminExists(admin.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdentityUserId"] = new SelectList(_context.Set<IdentityUser>(), "Id", "Id", admin.IdentityUserId);
            return View(admin);
        }

        // GET: Admins/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var admin = await _context.Admins
                .Include(a => a.IdentityUser)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (admin == null)
            {
                return NotFound();
            }

            return View(admin);
        }

        // POST: Admins/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var admin = await _context.Admins.FindAsync(id);
            _context.Admins.Remove(admin);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AdminExists(int id)
        {
            return _context.Admins.Any(e => e.Id == id);
        }

        public IActionResult AssignWork(int id)
        {
            List<Contractor> contractors = _context.Contractors.Select(c => c).ToList();
            var job = _context.WorkOrders.Where(j => j.Id == id).FirstOrDefault();
            ViewData["Contractors"] = new SelectList(contractors, "Id", "Type");
            return View(job);
        }
        [HttpPost]
        public IActionResult AssignWork(int id, WorkOrder job)
        {
            _context.WorkOrders.Update(job);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult ViewRecs()
        {
            var recs = _context.Reccomendations.Select(r => r).Include(r => r.Property).ToList();
            return View(recs);
        }
        
        public IActionResult RecDetails(int id)
        {
            var rec = _context.Reccomendations.Where(r => r.Id == id).Include(r => r.Property).FirstOrDefault();
            return View(rec);
        }

        public IActionResult CreateProperty()
        {
            Property property = new Property();
            return View(property);
        }
        [HttpPost]
        public async Task<IActionResult> CreateProperty(Property property)
        {
            var Addr = property.Address + ", " + property.City + ", " + property.State + ", " + property.ZipCode;
            HttpResponseMessage response = await httpClient.GetAsync("https://maps.googleapis.com/maps/api/geocode/json?address=" + Addr + "&key=" + API_Key.APIKEY);
            var result = await response.Content.ReadAsStringAsync();
            var parseResult = JObject.Parse(result);
            var lat = parseResult["results"][0]["geometry"]["location"]["lat"].Value<double>();
            var lng = parseResult["results"][0]["geometry"]["location"]["lng"].Value<double>();
            property.lat = lat;
            property.lng = lng;
            property.IsOccupied = false;
            _context.Properties.Add(property);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

PropertyManager/Views/Admins/AssignWork.cshtml
@model PropertyManager.Models.WorkOrder

@{
    ViewData["Title"] = "AssignWork";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>AssignWork</h1>

<h4>WorkOrder</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AssignWork">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Issue" class="control-label"></label>
                <input asp-for="Issue" class="form-control" />
                <span asp-validation-for="Issue" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsComplete" /> @Html.DisplayNameFor(model => model.IsComplete)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="TenantId" class="control-label"></label>
                <input asp-for="TenantId" class="form-control" />
                <span asp-validation-for="TenantId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContractorId" class="control-label"></label>
                <select asp-for="ContractorId" class="form-control" asp-items="ViewBag.Contractors "></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PropertyManager/Views/Admins/Create.cshtml
@model PropertyManager.Models.Admin

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Admin</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PropertyManager/Views/Admins/CreateProperty.cshtml
@model PropertyManager.Models.Property

@{
    ViewData["Title"] = "CreateProperty";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create Property</h1>

<h4>Property</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateProperty">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="State" class="control-label"></label>
                <input asp-for="State" class="form-control" />
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ZipCode" class="control-label"></label>
                <input asp-for="ZipCode" class="form-control" />
                <span asp-validation-for="ZipCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

PropertyManager/Views/Admins/Delete.cshtml
@model PropertyManager.Models.Admin

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Admin</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdentityUser)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdentityUser.Id)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PropertyManager/Views/Admins/Details.cshtml
@model PropertyManager.Models.WorkOrder

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>WorkOrder</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Issue)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Issue)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IsComplete)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IsComplete)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TenantId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TenantId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ContractorId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ContractorId)
        </dd>
    </dl>
</div>
<div>
   
    <a asp-action="Index">Back to List</a>
</div>
<div class="row">
    <div class="col">
        <div onload="initialize()" id="map" style="height: 600px; width: 650px ;"></div>
    </div>
</div>

<script>

        var map;
       function initMap() {
        var myLatLng = {lat: @Model.Tenant.Property.lat, lng: @Model.Tenant.Property.lng};

        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 15,
          center: myLatLng
        });

        var marker = new google.maps.Marker({
          position: myLatLng,
          map: map,
          title: 'Hello World!'
        });
      }

</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=@API_Key.APIKEY&callback=initMap"></script>

PropertyManager/Views/Admins/Edit.cshtml
@model PropertyManager.Models.Admin

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Admin</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="IdentityUserId" class="control-label"></label>
                <select asp-for="IdentityUserId" class="form-control" asp-items="ViewBag.IdentityUserId"></select>
                <span asp-validation-for="IdentityUserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PropertyManager/Views/Admins/Index.cshtml
@model IEnumerable<PropertyManager.Models.WorkOrder>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Home</h1>

<p>
        <a asp-action="CreateProperty">Create New Property</a>
    </p>
<div class="row">
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Issue)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.IsComplete)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TenantId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ContractorId)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Issue)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IsComplete)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TenantId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ContractorId)
                    </td>
                    <td>
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        <a asp-action="AssignWork" asp-route-id="@item.Id">Assign</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div class="row">
    <div class="col">
        <input type="button" value="Reccomendations" class="btn btn-secondary" onclick="location.href='@Url.Action("ViewRecs", "Admins")'" />
    </div>
</div>
<div class="row">
    <div class="col">
        <div onload="initialize()" id="map" style="height: 600px; width: 650px ;"></div>
    </div>
</div>

<script>
    var coords = [];
    @foreach (var item in Model)
    {
        <text>
    myLatLng = { lat: @item.Tenant.Property.lat, lng: @item.Tenant.Property.lng};
    coords.push(myLatLng);
    </text>
    }
    var map;
       function initMap() {
        @*var myLatLng = {lat: @Model.Tenant.Property.lat, lng: @Model.Property.lng};*@

        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 10,
            center: coords[0]
        });

           @foreach (var item in Model)
           {
                   <text>
           var marker = new google.maps.Marker({
               position: {lat: @item.Tenant.Property.lat, lng: @item.Tenant.Property.lng},
                  map: map,
                  title:'Work Order: ' + '@item.Id'
                   });
           </text>
           }
               
      }

</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=@API_Key.APIKEY&callback=initMap"></script>

PropertyManager/Views/Admins/RecDetails.cshtml
@model PropertyManager.Models.Reccomendation

@{
    ViewData["Title"] = "RecDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Reccomendation Details</h1>

<div>
    <h4>Reccomendation</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Rec)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Rec)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Property.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Property.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Property.Address)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Property.Address)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Property.City)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Property.City)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Property.State)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Property.State)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Property.ZipCode)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Property.ZipCode)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>
<div class="row">
    <div class="col">
        <div onload="initialize()" id="map" style="height: 600px; width: 650px ;"></div>
    </div>
</div>

<script>

        var map;
       function initMap() {
        var myLatLng = {lat: @Model.Property.lat, lng: @Model.Property.lng};

        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 15,
          center: myLatLng
        });

        var marker = new google.maps.Marker({
          position: myLatLng,
          map: map,
          title: 'Hello World!'
        });
      }

</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=@API_Key.APIKEY&callback=initMap"></script>

PropertyManager/Views/Admins/ViewRecs.cshtml
@model IEnumerable<PropertyManager.Models.Reccomendation>

@{
    ViewData["Title"] = "ViewRecs";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Reccomendations</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Property.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Property.Name)
            </td>
            <td>
                <a asp-action="RecDetails" asp-route-id="@item.Id">Details</a> 
            </td>
        </tr>
}
    </tbody>
</table>